version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongo-db
    networks:
      - compose-bridge
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=M0nG0
      - MONGO_INITDB_ROOT_DATABASE=preacher

  app:
    container_name: app-node
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - compose-bridge
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=preacher

    depends_on:
      - mongodb

networks:
  compose-bridge:
    driver: bridge

volumes:
  mongodb_data:
